### ISSUE TITLE
Demo代码高亮失效

### ISSUE THREAD

**Issue by weakish** [ksky521/mpeditor#4]
[Demo](http://js8.in/mpeditor/)的代码高亮失效了。

浏览器：

1. Safari Version 11.0 (12604.1.38.1.7)
2. Vivaldi 1.12.955.48 (on OSX)

**Comment by GeneralLi95** [comment]
同样遇到这个问题，代码高亮还是用不了的

**Comment by ksky521** [comment]
修复了
